### ISSUE TITLE
Istancing new Tmdb launches excpetion

### ISSUE THREAD

**Issue by SkidrowDev01** [UweTrottmann/tmdb-java#20]
Thanks for your great work.
After build the maven project and so adding the built jar as library my project runs in excpetion due to:
<code>
Caused by: java.lang.ClassNotFoundException: retrofit.converter.Converter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
</code>
Any help? All libraries has been correctly downloaded.
Thank you

**Comment by UweTrottmann** [comment]
First of all, I strongly suggest you include tmdb-java via a [Maven](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) or [Gradle](http://www.gradle.org/docs/current/userguide/dependency_management.html#sub:module_dependencies) dependency (see the [README](https://github.com/UweTrottmann/tmdb-java/blob/master/README.md#usage)).

If you still want to use a `jar` make sure to include any required dependencies (retrofit, etc.). They are listed in the [README](https://github.com/UweTrottmann/tmdb-java/blob/master/README.md#dependencies) as well.
